#!/bin/bash
set -e

cd "$(dirname "$0")/.."

ENV_DEPLOY_FILE=".env.deploy"
FRONTEND_ENV="../frontend/.env"

echo "==================================="
echo "Writers Almanac - Backend Deployment"
echo "==================================="
echo ""

# Load from .env.deploy if it exists
if [ -f "$ENV_DEPLOY_FILE" ]; then
    echo "Loading configuration from $ENV_DEPLOY_FILE..."
    export $(grep -v '^#' "$ENV_DEPLOY_FILE" | grep -v '^$' | xargs)
fi

# Get region with default
DEFAULT_REGION="${AWS_REGION:-us-west-1}"
read -p "AWS Region [$DEFAULT_REGION]: " input_region
AWS_REGION="${input_region:-$DEFAULT_REGION}"

# Get stack name with default
DEFAULT_STACK="${STACK_NAME:-writers-almanac-backend-prod}"
read -p "Stack Name [$DEFAULT_STACK]: " input_stack
STACK_NAME="${input_stack:-$DEFAULT_STACK}"

# Get environment with default
DEFAULT_ENV="${ENVIRONMENT:-prod}"
read -p "Environment (dev/staging/prod) [$DEFAULT_ENV]: " input_env
ENVIRONMENT="${input_env:-$DEFAULT_ENV}"

# Get S3 bucket name
echo ""
echo "--- S3 Data Bucket ---"
echo "This bucket contains the author/poem data (pre-existing, not managed by SAM)"
echo ""

DEFAULT_BUCKET="${S3_BUCKET_NAME:-}"
if [ -n "$S3_BUCKET_NAME" ]; then
    echo "S3 Bucket: [$S3_BUCKET_NAME - press Enter to keep]"
else
    echo "S3 Bucket: [not set - required]"
fi
read -p "> " input_bucket
S3_BUCKET_NAME="${input_bucket:-$S3_BUCKET_NAME}"

if [ -z "$S3_BUCKET_NAME" ]; then
    echo "ERROR: S3 bucket name is required"
    exit 1
fi

# Save configuration
cat > "$ENV_DEPLOY_FILE" << EOF
# Deployment configuration (auto-saved)
AWS_REGION=$AWS_REGION
STACK_NAME=$STACK_NAME
ENVIRONMENT=$ENVIRONMENT
S3_BUCKET_NAME=$S3_BUCKET_NAME
EOF
echo ""
echo "Configuration saved to $ENV_DEPLOY_FILE"

# Generate samconfig.toml
DEPLOY_BUCKET="sam-deploy-writers-almanac-${AWS_REGION}"

cat > "samconfig.toml" << EOF
# SAM CLI configuration file (auto-generated from .env.deploy)
# Re-run ./scripts/deploy.sh to regenerate this file

version = 0.1

[default.deploy.parameters]
stack_name = "$STACK_NAME"
s3_bucket = "$DEPLOY_BUCKET"
s3_prefix = "$STACK_NAME"
region = "$AWS_REGION"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Environment=$ENVIRONMENT S3BucketName=$S3_BUCKET_NAME"
EOF
echo "Updated samconfig.toml"

echo ""
echo "Using configuration:"
echo "  Region: $AWS_REGION"
echo "  Stack Name: $STACK_NAME"
echo "  Environment: $ENVIRONMENT"
echo "  S3 Data Bucket: $S3_BUCKET_NAME"
echo ""

# Create deployment bucket if needed
echo "==================================="
echo "Step 1: Setup Deployment Bucket"
echo "==================================="

if ! aws s3 ls "s3://${DEPLOY_BUCKET}" --region "$AWS_REGION" 2>/dev/null; then
    echo "Creating deployment bucket: ${DEPLOY_BUCKET}"
    aws s3 mb "s3://${DEPLOY_BUCKET}" --region "$AWS_REGION"
else
    echo "Deployment bucket exists: ${DEPLOY_BUCKET}"
fi

echo ""
echo "==================================="
echo "Step 2: Build SAM Application"
echo "==================================="
echo ""
sam build --template template.yaml

echo ""
echo "==================================="
echo "Step 3: Deploy Stack"
echo "==================================="
echo ""

sam deploy \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --s3-bucket "$DEPLOY_BUCKET" \
    --s3-prefix "$STACK_NAME" \
    --capabilities CAPABILITY_IAM \
    --parameter-overrides "Environment=$ENVIRONMENT" "S3BucketName=$S3_BUCKET_NAME" \
    --no-confirm-changeset \
    --no-fail-on-empty-changeset

echo ""
echo "==================================="
echo "Deployment Complete!"
echo "==================================="
echo ""

# Get stack outputs
API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
    --output text 2>/dev/null || echo "")

echo "Stack Outputs:"
echo "  API URL: $API_URL"
echo ""

# Update frontend .env file
update_env_var() {
    local key=$1
    local value=$2
    local file=$3

    if [ -z "$value" ] || [ "$value" = "None" ]; then
        return
    fi

    if grep -q "^${key}=" "$file" 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    else
        echo "${key}=${value}" >> "$file"
    fi
}

# Create frontend/.env if it doesn't exist
if [ ! -f "$FRONTEND_ENV" ]; then
    cat > "$FRONTEND_ENV" << EOF
# AWS Configuration (auto-generated by deploy.sh)
VITE_API_BASE_URL=$API_URL
VITE_AWS_REGION=$AWS_REGION
VITE_S3_BUCKET=$S3_BUCKET_NAME
EOF
    echo "Created frontend .env file"
else
    update_env_var "VITE_API_BASE_URL" "$API_URL" "$FRONTEND_ENV"
    update_env_var "VITE_AWS_REGION" "$AWS_REGION" "$FRONTEND_ENV"
    update_env_var "VITE_S3_BUCKET" "$S3_BUCKET_NAME" "$FRONTEND_ENV"
    echo "Updated frontend .env file"
fi

echo ""
echo "Done! Frontend .env has been updated with stack outputs."
echo "  Path: frontend/.env"
echo ""
echo "To run the frontend locally:"
echo "  npm run dev"
