/**
 * TanStack Query hook for the set of broadcast dates that have a recording.
 *
 * Audio availability used to be inferred from the date alone — anything after
 * 2009-01-11 was assumed to have a recording. Measured against the bucket, 96
 * of the 3,244 broadcasts after that cutoff have no `.mp3` at all, 94 of them
 * in 2014. The guess was wrong about 3% of the time, always in the direction of
 * promising audio that is not there.
 *
 * The archive is frozen, so the real set is fixed: 3,149 dates, ~6 kB gzipped,
 * generated by `scripts/generate-audio-index.mjs` and fetched once per session.
 */

import { useQuery, UseQueryResult } from '@tanstack/react-query';

/** Where the generated asset is served from, relative to the app's own origin */
export const AUDIO_DATES_URL = '/audio-dates.json';

/** Query key factory for the audio-date set */
export const audioDatesKeys = {
  all: ['audioDates'] as const,
};

/**
 * Fetch the audio-date manifest.
 *
 * @param signal - Aborts the request when the caller goes away
 * @returns Broadcast dates in YYYYMMDD form that have a recording
 * @throws When the asset cannot be fetched or is not an array of YYYYMMDD strings
 */
export async function fetchAudioDates(signal?: AbortSignal): Promise<ReadonlySet<string>> {
  const response = await fetch(AUDIO_DATES_URL, { signal });
  if (!response.ok) {
    throw new Error(`Audio date manifest request failed: ${response.status}`);
  }

  const data: unknown = await response.json();
  if (!Array.isArray(data) || data.some(entry => !isBroadcastDate(entry))) {
    throw new Error('Audio date manifest is malformed');
  }

  return new Set(data as string[]);
}

/**
 * Every entry must be the YYYYMMDD the generator emits.
 *
 * Checking the shape rather than just the type matters because the consumers
 * look these up by exact string: a manifest of ISO dates, or of numbers coerced
 * to strings, would match nothing and silently un-highlight the whole archive
 * rather than failing.
 */
function isBroadcastDate(value: unknown): value is string {
  return typeof value === 'string' && /^\d{8}$/.test(value);
}

/**
 * The dates that have a recording, or undefined until the manifest lands.
 *
 * Consumers should treat `undefined` asymmetrically, because the two callers
 * want opposite failure behaviour: the author page must not promise audio it
 * cannot confirm, while the player may as well attempt the URL — attempting and
 * failing is no worse than never trying.
 *
 * @example
 * const { data: audioDates } = useAudioDatesQuery();
 * const hasAudio = audioDates?.has('20150325') ?? false;
 */
export function useAudioDatesQuery(): UseQueryResult<ReadonlySet<string>, Error> {
  return useQuery<ReadonlySet<string>, Error>({
    queryKey: audioDatesKeys.all,
    queryFn: ({ signal }) => fetchAudioDates(signal),
    staleTime: Infinity,
    gcTime: Infinity,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });
}
