/**
 * Search Index
 *
 * A client-side index of every searchable thing in the archive: author names
 * and poem titles. Every suggestion knows whether it is an author or a poem —
 * which is what lets the UI label a result and route it without a second lookup.
 *
 * Matching is forgiving on purpose: case, accents and punctuation are stripped
 * before comparing, so "billy collins", "Billy Collins" and "BILLY  COLLINS"
 * all resolve to the same target.
 *
 * WHERE THE DATA COMES FROM: the 7,572 labels are fetched as a static JSON
 * asset rather than imported. Importing them compiled 67 kB gzipped into the
 * entry chunk, so every visitor paid for the whole archive index before first
 * paint — including someone who reads today's poem and leaves. The asset is
 * generated by `scripts/generate-search-index.mjs` and served from the same
 * origin as the app.
 *
 * The module holds no data of its own: `createSearchIndex` builds an index from
 * whatever it is handed, which keeps the ranking logic synchronous and directly
 * testable against fixtures or against the real lists.
 */

/** What a search result points at */
export type SearchTargetType = 'author' | 'poem';

/**
 * The minimum needed to navigate somewhere - what callers outside the index
 * (a byline click, a URL) can produce without consulting the index.
 */
export interface SearchTargetRef {
  /** Canonical name, exactly as it appears in the archive */
  label: string;
  type: SearchTargetType;
}

/** An indexed target, ready to render as a suggestion */
export interface SearchTarget extends SearchTargetRef {
  /** Stable unique key - an author and a poem can share a name */
  key: string;
  /** Comparison form: lowercased, unaccented, punctuation collapsed to spaces */
  normalized: string;
}

/** The shape of the generated JSON asset */
export interface SearchIndexData {
  authors: readonly string[];
  poems: readonly string[];
}

/** Suggestions rendered at once. Enough to scroll, few enough to stay fast. */
export const MAX_SUGGESTIONS = 40;

/** Where the generated asset is served from, relative to the app's own origin */
export const SEARCH_INDEX_URL = '/search-index.json';

/**
 * Reduce a string to its comparison form.
 *
 * @param value - Raw user input or archive label
 * @returns Lowercase, accent-free text with punctuation collapsed to single spaces
 *
 * @example
 * normalizeSearchText("Edna St. Vincent Millay") // 'edna st vincent millay'
 * normalizeSearchText("  Rilke's  Elegy ") // 'rilke s elegy'
 */
export function normalizeSearchText(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function toTarget(label: string, type: SearchTargetType): SearchTarget {
  return {
    label,
    type,
    key: `${type}:${label}`,
    normalized: normalizeSearchText(label),
  };
}

/** How a target matched, lower being better on both axes */
interface MatchQuality {
  /** 0 exact, 1 starts a word, 2 buried mid-word */
  bucket: number;
  /** Within a bucket: 0 starts the label, 1 starts a later word */
  position: number;
}

/**
 * Score how a target matches a query, or null when it does not match.
 *
 * Starting the label and starting any word share a bucket so that type can
 * break the tie: searching "frost" should reach Robert Frost before it reaches
 * a poem called "Frost at Midnight".
 */
function matchTarget(target: SearchTarget, normalizedQuery: string): MatchQuality | null {
  const { normalized } = target;

  if (normalized === normalizedQuery) return { bucket: 0, position: 0 };
  if (normalized.startsWith(normalizedQuery)) return { bucket: 1, position: 0 };

  // A match starting any word ("frost" in "Robert Frost") beats one buried
  // mid-word ("frost" in "Defrosting"). Every occurrence is considered, not
  // just the first: "ri" starts a word in "Adrienne Rich" even though it also
  // appears mid-word earlier.
  if (normalized.includes(` ${normalizedQuery}`)) return { bucket: 1, position: 1 };
  if (normalized.includes(normalizedQuery)) return { bucket: 2, position: 1 };

  return null;
}

/** Authors sort ahead of poems when relevance ties */
function typeRank(target: SearchTarget): number {
  return target.type === 'author' ? 0 : 1;
}

/** A built index. All lookups are synchronous once the data has arrived. */
export interface SearchIndex {
  /** Author names in archive order, for stepping through neighbours */
  readonly authors: readonly string[];
  /** Poem titles in archive order, for stepping through neighbours */
  readonly poems: readonly string[];

  /** Whether the archive has an author by exactly this name */
  hasAuthor(name: string): boolean;
  /** Whether the archive has a poem by exactly this title */
  hasPoemTitle(title: string): boolean;

  /**
   * Every indexed target, authors first. Built on first call and reused after,
   * since normalizing ~7,500 labels costs a few milliseconds.
   */
  getTargets(): SearchTarget[];

  /**
   * Look up the indexed target for an exact label and type.
   *
   * Type matters: a label can exist as both an author and a poem, and resolving
   * by text alone would silently pick one of them.
   */
  findTarget(ref: SearchTargetRef): SearchTarget | null;

  /**
   * Find targets matching a query, best match first.
   *
   * The ordering here is also the ordering the dropdown renders, so the first
   * result is always what pressing Enter selects.
   */
  searchTargets(query: string, limit?: number): SearchTarget[];

  /** Resolve free text to the single target a search should navigate to. */
  resolveSearchTarget(query: string): SearchTarget | null;
}

/**
 * Build an index over a set of labels.
 *
 * @param data - Author names and poem titles, as the generated asset supplies them
 * @returns An index whose lookups are synchronous
 *
 * @example
 * const index = createSearchIndex({ authors: ['Billy Collins'], poems: ['The Lanyard'] });
 * index.searchTargets('lanyard')[0].type // 'poem'
 */
export function createSearchIndex(data: SearchIndexData): SearchIndex {
  const { authors, poems } = data;

  const authorNames: ReadonlySet<string> = new Set(authors);
  const poemTitles: ReadonlySet<string> = new Set(poems);

  // Normalizing ~7,500 labels costs a few milliseconds, so it is deferred until
  // the first search rather than run when the index is created.
  let cachedTargets: SearchTarget[] | null = null;
  let targetsByKey: Map<string, SearchTarget> | null = null;

  function allTargets(): SearchTarget[] {
    if (!cachedTargets) {
      cachedTargets = [
        ...authors.map(name => toTarget(name, 'author')),
        ...poems.map(title => toTarget(title, 'poem')),
      ];
    }
    return cachedTargets;
  }

  function searchTargets(query: string, limit: number = MAX_SUGGESTIONS): SearchTarget[] {
    const normalizedQuery = normalizeSearchText(query);
    if (!normalizedQuery) return [];

    const matches: Array<{ target: SearchTarget; quality: MatchQuality }> = [];
    for (const target of allTargets()) {
      const quality = matchTarget(target, normalizedQuery);
      if (quality) {
        matches.push({ target, quality });
      }
    }

    matches.sort(
      (a, b) =>
        a.quality.bucket - b.quality.bucket ||
        typeRank(a.target) - typeRank(b.target) ||
        a.quality.position - b.quality.position ||
        a.target.label.localeCompare(b.target.label)
    );

    return matches.slice(0, limit).map(match => match.target);
  }

  return {
    authors,
    poems,

    hasAuthor: name => authorNames.has(name),
    hasPoemTitle: title => poemTitles.has(title),

    getTargets: allTargets,

    findTarget({ label, type }: SearchTargetRef): SearchTarget | null {
      if (!targetsByKey) {
        targetsByKey = new Map(allTargets().map(target => [target.key, target]));
      }
      return targetsByKey.get(`${type}:${label}`) ?? null;
    },

    searchTargets,

    resolveSearchTarget(query: string): SearchTarget | null {
      return searchTargets(query, 1)[0] ?? null;
    },
  };
}

/**
 * Fetch the generated index asset and build an index from it.
 *
 * @param signal - Aborts the request when the caller goes away
 * @returns The built index
 * @throws When the asset cannot be fetched or does not hold two string arrays
 */
export async function fetchSearchIndex(signal?: AbortSignal): Promise<SearchIndex> {
  const response = await fetch(SEARCH_INDEX_URL, { signal });
  if (!response.ok) {
    throw new Error(`Search index request failed: ${response.status}`);
  }

  const data: unknown = await response.json();
  if (!isSearchIndexData(data)) {
    throw new Error('Search index asset is malformed');
  }

  return createSearchIndex(data);
}

function isSearchIndexData(value: unknown): value is SearchIndexData {
  if (typeof value !== 'object' || value === null) return false;
  const { authors, poems } = value as Partial<SearchIndexData>;
  return (
    Array.isArray(authors) &&
    Array.isArray(poems) &&
    authors.every(entry => typeof entry === 'string') &&
    poems.every(entry => typeof entry === 'string')
  );
}
